title: Algorithms && Data Structures
email: ""
description: "Illustrations for Common Algorithms and Data Structures."
baseurl: "/Algorithms" # the subpath of your site, e.g. /blog
url: "https://Zeqiang-Lai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Zeqiang-Lai


# Build settings
permalink: none
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
display-site-nav: true